import type { MenuItem, RestaurantTable } from "@/lib/api/types";

/* Menu and tables are seeded here because the MVP spec keeps them
   out of the product UI (docs/2-mvp-ideation.md → "menu items and tables
   are added directly in the Supabase dashboard").

   The menu is stocked so every cuisine lib/diner/menu-atlas builds is a real
   menu: six sections, at least seven dishes each, with egg and non-veg lines
   so the diet filters (lib/diner/diet) all have something to find. Each dish's
   `category` is the section it sits under, which is also the cuisine's single
   section — so opening a cuisine lands straight on its dishes. */

export const seedTables: RestaurantTable[] = [
  { id: "tbl_k7x2p", code: "k7x2p", name: "Window four-top" },
  { id: "tbl_m3q8z", code: "m3q8z", name: "Corner booth" },
  { id: "tbl_v9w1s", code: "v9w1s", name: "Communal table" },
];

export const seedMenu: MenuItem[] = [
  /* ---- South Indian ---------------------------------------------------- */
  {
    id: "itm_dosa",
    name: "Masala Dosa",
    price: 180,
    category: "South Indian",
    is_available: true,
    description: "Crisp rice crepe, potato masala, coconut chutney.",
    vegetarian: true,
  },
  {
    id: "itm_idli",
    name: "Idli Sambar",
    price: 140,
    category: "South Indian",
    is_available: true,
    description: "Steamed rice cakes, lentil sambar, coconut chutney.",
    vegetarian: true,
  },
  {
    id: "itm_vada",
    name: "Medu Vada",
    price: 150,
    category: "South Indian",
    is_available: true,
    description: "Crisp gram-flour doughnuts with coconut chutney.",
    vegetarian: true,
  },
  {
    id: "itm_uttapam",
    name: "Onion Uttapam",
    price: 190,
    category: "South Indian",
    is_available: true,
    description: "Thick rice pancake with onion and green chilli.",
    vegetarian: true,
  },
  {
    id: "itm_rava_dosa",
    name: "Rava Dosa",
    price: 200,
    category: "South Indian",
    is_available: true,
    description: "Lacy semolina crepe, ghee, coconut chutney.",
    vegetarian: true,
  },
  {
    id: "itm_pongal",
    name: "Ven Pongal",
    price: 170,
    category: "South Indian",
    is_available: true,
    description: "Rice and moong dal, ghee, black pepper, cashew.",
    vegetarian: true,
  },
  {
    id: "itm_rasam",
    name: "Tomato Rasam",
    price: 130,
    category: "South Indian",
    is_available: true,
    description: "Tamarind tomato broth, curry leaf, mustard seeds.",
    vegetarian: true,
  },
  {
    id: "itm_egg_dosa",
    name: "Egg Dosa",
    price: 210,
    category: "South Indian",
    is_available: true,
    description: "Crisp crepe layered with a spiced omelette.",
    vegetarian: false,
  },

  /* ---- Indo-Chinese ---------------------------------------------------- */
  {
    id: "itm_noodles",
    name: "Veg Hakka Noodles",
    price: 240,
    category: "Indo-Chinese",
    is_available: true,
    description: "Wok-tossed noodles with seasonal vegetables.",
    vegetarian: true,
  },
  {
    id: "itm_manchurian",
    name: "Veg Manchurian",
    price: 250,
    category: "Indo-Chinese",
    is_available: true,
    description: "Crisp vegetable balls in a glossy garlic sauce.",
    vegetarian: true,
  },
  {
    id: "itm_chowmein",
    name: "Schezwan Chowmein",
    price: 230,
    category: "Indo-Chinese",
    is_available: true,
    description: "Stir-fried noodles, schezwan pepper, spring onion.",
    vegetarian: true,
  },
  {
    id: "itm_fried_rice",
    name: "Veg Fried Rice",
    price: 220,
    category: "Indo-Chinese",
    is_available: true,
    description: "Wok-charred rice, garden vegetables, soy.",
    vegetarian: true,
  },
  {
    id: "itm_spring_roll",
    name: "Veg Spring Rolls",
    price: 200,
    category: "Indo-Chinese",
    is_available: true,
    description: "Crisp rolls, glass noodles, sweet chilli dip.",
    vegetarian: true,
  },
  {
    id: "itm_gobi",
    name: "Gobi Manchurian",
    price: 240,
    category: "Indo-Chinese",
    is_available: true,
    description: "Cauliflower tossed in a sticky chilli glaze.",
    vegetarian: true,
  },
  {
    id: "itm_chilli_noodles",
    name: "Chilli Garlic Noodles",
    price: 260,
    category: "Indo-Chinese",
    is_available: true,
    description: "Smoky noodles with burnt chilli and garlic.",
    vegetarian: true,
  },
  {
    id: "itm_egg_fried_rice",
    name: "Egg Fried Rice",
    price: 250,
    category: "Indo-Chinese",
    is_available: true,
    description: "Fried rice folded through scrambled egg.",
    vegetarian: false,
  },

  /* ---- North Indian ---------------------------------------------------- */
  {
    id: "itm_paneer",
    name: "Paneer Butter Masala",
    price: 320,
    category: "North Indian",
    is_available: true,
    description: "Paneer in a slow-cooked tomato and cashew gravy.",
    vegetarian: true,
  },
  {
    id: "itm_naan",
    name: "Garlic Naan",
    price: 90,
    category: "North Indian",
    is_available: true,
    description: "Tandoor naan brushed with garlic butter.",
    vegetarian: true,
  },
  {
    id: "itm_roti",
    name: "Tandoori Roti",
    price: 60,
    category: "North Indian",
    is_available: true,
    description: "Whole wheat roti straight off the tandoor.",
    vegetarian: true,
  },
  {
    id: "itm_dal",
    name: "Dal Makhani",
    price: 280,
    category: "North Indian",
    is_available: true,
    description: "Black lentils simmered overnight with garlic and cream.",
    vegetarian: true,
  },
  {
    id: "itm_paneer_tikka",
    name: "Paneer Tikka",
    price: 300,
    category: "North Indian",
    is_available: true,
    description: "Charred paneer, capsicum, mint chutney.",
    vegetarian: true,
  },
  {
    id: "itm_kofta",
    name: "Veg Kofta Curry",
    price: 290,
    category: "North Indian",
    is_available: true,
    description: "Vegetable dumplings in a saffron cashew curry.",
    vegetarian: true,
  },
  {
    id: "itm_kulcha",
    name: "Chole Kulcha",
    price: 260,
    category: "North Indian",
    is_available: true,
    description: "Spiced chickpeas with a stuffed griddle kulcha.",
    vegetarian: true,
  },
  {
    id: "itm_chicken_tikka",
    name: "Chicken Tikka Masala",
    price: 380,
    category: "North Indian",
    is_available: true,
    description: "Tandoor chicken in a smoky tomato masala.",
    vegetarian: false,
  },
  {
    id: "itm_egg_curry",
    name: "Egg Curry",
    price: 280,
    category: "North Indian",
    is_available: true,
    description: "Boiled egg in an onion tomato curry.",
    vegetarian: false,
  },

  /* ---- Biryani & Rice -------------------------------------------------- */
  {
    id: "itm_biryani",
    name: "Hyderabadi Biryani",
    price: 380,
    category: "Biryani & Rice",
    is_available: true,
    description: "Dum-cooked basmati, saffron, fried onions, raita.",
    vegetarian: false,
  },
  {
    id: "itm_veg_biryani",
    name: "Veg Biryani",
    price: 320,
    category: "Biryani & Rice",
    is_available: true,
    description: "Dum-cooked basmati, garden vegetables, mint.",
    vegetarian: true,
  },
  {
    id: "itm_chicken_biryani",
    name: "Chicken Biryani",
    price: 400,
    category: "Biryani & Rice",
    is_available: true,
    description: "Slow-cooked basmati, chicken, fried onion, raita.",
    vegetarian: false,
  },
  {
    id: "itm_pulao",
    name: "Peas Pulao",
    price: 220,
    category: "Biryani & Rice",
    is_available: true,
    description: "Basmati with green peas and whole spice.",
    vegetarian: true,
  },
  {
    id: "itm_jeera_rice",
    name: "Jeera Rice",
    price: 180,
    category: "Biryani & Rice",
    is_available: true,
    description: "Basmati tempered with cumin and ghee.",
    vegetarian: true,
  },
  {
    id: "itm_curd_rice",
    name: "Curd Rice",
    price: 190,
    category: "Biryani & Rice",
    is_available: true,
    description: "Cooling rice with yogurt and pomegranate.",
    vegetarian: true,
  },
  {
    id: "itm_lemon_rice",
    name: "Lemon Rice",
    price: 180,
    category: "Biryani & Rice",
    is_available: true,
    description: "Rice tossed with lemon and roasted peanut.",
    vegetarian: true,
  },

  /* ---- Starters -------------------------------------------------------- */
  {
    id: "itm_tacos",
    name: "Masala Tacos",
    price: 260,
    category: "Starters",
    is_available: true,
    description: "Three soft tacos, cumin slaw, smoked chilli.",
    vegetarian: true,
  },
  {
    id: "itm_burger",
    name: "Chhotu Burger",
    price: 290,
    category: "Starters",
    is_available: true,
    description: "House patty, pickled onion, warm brioche bun.",
    vegetarian: false,
  },
  {
    id: "itm_pakora",
    name: "Onion Pakora",
    price: 160,
    category: "Starters",
    is_available: true,
    description: "Crisp gram-flour fritters with mint chutney.",
    vegetarian: true,
  },
  {
    id: "itm_samosa",
    name: "Samosa Chaat",
    price: 180,
    category: "Starters",
    is_available: true,
    description: "Crushed samosa, yogurt, tamarind, sev.",
    vegetarian: true,
  },
  {
    id: "itm_fries",
    name: "Masala Fries",
    price: 170,
    category: "Starters",
    is_available: true,
    description: "Skin-on fries dusted with chaat masala.",
    vegetarian: true,
  },
  {
    id: "itm_momos",
    name: "Veg Momos",
    price: 190,
    category: "Starters",
    is_available: true,
    description: "Steamed dumplings, cabbage, fiery red chutney.",
    vegetarian: true,
  },
  {
    id: "itm_kebab",
    name: "Chicken Seekh Kebab",
    price: 320,
    category: "Starters",
    is_available: true,
    description: "Minced chicken skewers, mint chutney, onion rings.",
    vegetarian: false,
  },

  /* ---- Drinks & Desserts ----------------------------------------------- */
  {
    id: "itm_lassi",
    name: "Sweet Lassi",
    price: 120,
    category: "Drinks & Desserts",
    is_available: true,
    description: "Chilled hand-churned yogurt, rose, pistachio.",
    vegetarian: true,
  },
  {
    id: "itm_chai",
    name: "Masala Chai",
    price: 70,
    category: "Drinks & Desserts",
    is_available: true,
    description: "Assam leaf tea, ginger, cardamom.",
    vegetarian: true,
  },
  {
    id: "itm_kulfi",
    name: "Malai Kulfi",
    price: 140,
    category: "Drinks & Desserts",
    is_available: true,
    description: "Slow-reduced milk kulfi, saffron, almond.",
    vegetarian: true,
  },
  {
    id: "itm_coffee",
    name: "Filter Coffee",
    price: 80,
    category: "Drinks & Desserts",
    is_available: true,
    description: "Strong decoction, frothed milk, tumbler.",
    vegetarian: true,
  },
  {
    id: "itm_soda",
    name: "Fresh Lime Soda",
    price: 90,
    category: "Drinks & Desserts",
    is_available: true,
    description: "Lime, soda, a pinch of black salt.",
    vegetarian: true,
  },
  {
    id: "itm_jamun",
    name: "Gulab Jamun",
    price: 130,
    category: "Drinks & Desserts",
    is_available: true,
    description: "Warm milk dumplings in rose syrup.",
    vegetarian: true,
  },
  {
    id: "itm_falooda",
    name: "Mango Falooda",
    price: 160,
    category: "Drinks & Desserts",
    is_available: true,
    description: "Layered mango, vermicelli, basil seed, kulfi.",
    vegetarian: true,
  },
];
